spring.application.name=api-gateway
server.port=8765

spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true

spring.cloud.gateway.server.webflux.routes[0].id=quiz-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://quiz-service
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/quiz/**